#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

bspc config border_width 3
bspc config window_gap 15
bspc config top_padding 24 # top_padding is set equal to polybar's height
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# swallow capabilities https://github.com/JopStro/bspswallow
pgrep bspswallow || bspswallow &

bspc rule -a gazebo desktop='^8' state=floating
bspc rule -a Code desktop='^2'
bspc rule -a Brave-browser desktop='^1'
bspc rule -a Spotify state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off

# polybar defualt -r &
launch_polybar &
