#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

bspc config border_width 1
bspc config window_gap 15
bspc config top_padding 34 # top_padding is set equal to polybar's height
bspc config bottom_padding 27 # bottom_padding is set equal to polybar's height
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# swallow capabilities https://github.com/JopStro/bspswallow
pgrep bspswallow || bspswallow &

## Window rules
bspc rule -a Brave-browser desktop='^1' follow=on focus=on
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a gazebo desktop='^8'
bspc rule -a rviz2 desktop='^7' 
bspc rule -a Code desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Kitty:tty-clock desktop='9' flag=sticky flag=locked
# need to be floating
bspc rule -a Sxiv state=floating follow=on
bspc rule -a ncmpcpp state=floating follow=on
bspc rule -a Spotify state=floating follow=on

launch_polybar &
